# Generated by Django 2.0 on 2019-05-19 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loginname', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('tel', models.IntegerField(max_length=20, null=True)),
                ('cer', models.IntegerField(max_length=10, null=True)),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myappweb.user')),
            ],
        ),
    ]
