# Generated by Django 2.0 on 2019-05-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='cer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='tel',
            field=models.IntegerField(null=True),
        ),
    ]
