# Generated by Django 2.0 on 2019-06-15 01:41

from django.db import migrations, models
import myappweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('myappweb', '0002_auto_20190519_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cjdj_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dizhi', models.TextField(max_length=500)),
                ('lx', models.TextField(max_length=500)),
                ('mianji', models.FloatField()),
                ('zongjia', models.FloatField()),
                ('dj', models.FloatField()),
                ('cjdate', models.DateTimeField()),
                ('down', models.FileField(upload_to=myappweb.models.upload_to)),
            ],
        ),
    ]
